train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: E:/UtLoad/complete_ms_data
      repeat: 56
      cache: spectral
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 64
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 56

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: E:/UtLoad/complete_ms_data
      first_k: 10
      repeat: 56
      cache: spectral
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 64
      scale_max: 4
      sample_q: 2304
  batch_size: 56

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: inr

optimizer:
  name: adam
  args:
    lr: 0.0001
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
